version: "3"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=docker

  php:
    container_name: php
    build:
      context: ./docker
    volumes:
      - .:/usr/src/fruits
    environment:
      - "XDEBUG_CONFIG:client_host=docker.for.mac.localhost"
      - "PHP_IDE_CONFIG:serverName=FruitCompany"


